-- MySQL Script generated by MySQL Workbench
-- Fri 10 Nov 2017 01:42:54 PM -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wedge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wedge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wedge` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `wedge` ;

-- -----------------------------------------------------
-- Table `wedge`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedge`.`books` (
  `ID` BINARY(16) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Password` BINARY(60) NOT NULL,
  UNIQUE INDEX `UUID_UNIQUE` (`ID` ASC),
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedge`.`assets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedge`.`assets` (
  `ID` BINARY(16) NOT NULL,
  `Name` VARCHAR(175) NOT NULL,
  `Code` VARCHAR(45) NOT NULL COMMENT 'EX: BRL, BTC, USD, NASQ:GOOG, B3:PETR4',
  `Places` INT(1) NOT NULL,
  `Fmt` VARCHAR(255) NOT NULL,
  `BookID` BINARY(16) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `UUID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `Name_UNIQ` (`Name` ASC, `BookID` ASC),
  INDEX `fk_assets_1_idx` (`BookID` ASC),
  CONSTRAINT `fk_assets_1`
    FOREIGN KEY (`BookID`)
    REFERENCES `wedge`.`books` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedge`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedge`.`accounts` (
  `ID` BINARY(16) NOT NULL,
  `ParentID` BINARY(16) NOT NULL,
  `Name` VARCHAR(175) NOT NULL,
  `BookID` BINARY(16) NOT NULL,
  UNIQUE INDEX `UUID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `Name_UNIQ` (`Name` ASC, `BookID` ASC),
  INDEX `fk_accounts_1_idx` (`ParentID` ASC),
  INDEX `fk_accounts_2_idx` (`BookID` ASC),
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_accounts_1`
    FOREIGN KEY (`ParentID`)
    REFERENCES `wedge`.`accounts` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_accounts_2`
    FOREIGN KEY (`BookID`)
    REFERENCES `wedge`.`books` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedge`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedge`.`transactions` (
  `ID` BINARY(16) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `LocalDate` INT(8) NOT NULL,
  UNIQUE INDEX `UUID_UNIQUE` (`ID` ASC),
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedge`.`movements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedge`.`movements` (
  `ID` BINARY(16) NOT NULL,
  `AccountID` BINARY(16) NOT NULL,
  `AssetID` BINARY(16) NOT NULL,
  `TransactionID` BINARY(16) NOT NULL,
  `Amount` BIGINT NOT NULL,
  `Status` CHAR(1) NOT NULL DEFAULT 'P' COMMENT '(P)Planned;(D)Done;(C)Cancelled',
  `LocalDate` INT(8) NOT NULL COMMENT 'Y*1E4 + M*1E2 + D\nEx: 20171231 = 2017-12-31',
  `Notes` TEXT(65535) NOT NULL,
  UNIQUE INDEX `UUID_UNIQUE` (`ID` ASC),
  INDEX `fk_movements_1_idx` (`AssetID` ASC),
  INDEX `fk_movements_2_idx` (`AccountID` ASC),
  INDEX `fk_movements_3_idx` (`TransactionID` ASC),
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_movements_1`
    FOREIGN KEY (`AssetID`)
    REFERENCES `wedge`.`assets` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_movements_2`
    FOREIGN KEY (`AccountID`)
    REFERENCES `wedge`.`accounts` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_movements_3`
    FOREIGN KEY (`TransactionID`)
    REFERENCES `wedge`.`transactions` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedge`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedge`.`tags` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Table` VARCHAR(45) NOT NULL,
  `ItemUUID` BINARY(16) NOT NULL,
  `Tag` VARCHAR(160) NOT NULL,
  `BookUUID` BINARY(16) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UNIQ` (`ItemUUID` ASC, `Tag` ASC, `BookUUID` ASC),
  INDEX `fk_tags_1_idx` (`BookUUID` ASC),
  CONSTRAINT `fk_tags_1`
    FOREIGN KEY (`BookUUID`)
    REFERENCES `wedge`.`books` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedge`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedge`.`itens` (
  `ID` BINARY(16) NOT NULL,
  `AssetID` BINARY(16) NOT NULL,
  `TransactionID` BINARY(16) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `GenericName` VARCHAR(255) NOT NULL,
  `Unit` VARCHAR(45) NOT NULL,
  `Qty` FLOAT NOT NULL,
  `UnitCost` BIGINT NOT NULL,
  `TotalCost` BIGINT NOT NULL,
  `PeriodStart` INT(8) NOT NULL COMMENT 'Y*1E4 + M*1E2 + D\nEx: 20171231 = 2017-12-31',
  `PeriodEnd` INT(8) NOT NULL COMMENT 'Y*1E4 + M*1E2 + D\nEx: 20171231 = 2017-12-31',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `UUID_UNIQUE` (`ID` ASC),
  INDEX `fk_itens_1_idx` (`TransactionID` ASC),
  CONSTRAINT `fk_itens_1`
    FOREIGN KEY (`TransactionID`)
    REFERENCES `wedge`.`assets` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_itens_2`
    FOREIGN KEY (`TransactionID`)
    REFERENCES `wedge`.`transactions` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedge`.`aseets_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedge`.`aseets_values` (
  `ID` BINARY(16) NOT NULL,
  `AssetID` BINARY(16) NOT NULL,
  `BaseID` BINARY(16) NOT NULL,
  `AssetInBase` FLOAT NOT NULL,
  `LocalDate` INT(8) NOT NULL,
  UNIQUE INDEX `UUID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `UNIQ` (`BaseID` ASC, `AssetID` ASC, `LocalDate` ASC),
  INDEX `fk_aseets_value_1_idx` (`AssetID` ASC),
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_aseets_value_1`
    FOREIGN KEY (`AssetID`)
    REFERENCES `wedge`.`assets` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aseets_values_1`
    FOREIGN KEY (`BaseID`)
    REFERENCES `wedge`.`assets` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
