-- MySQL Script generated by MySQL Workbench
-- Fri 06 Oct 2017 06:30:38 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `UUID` BINARY(16) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Key` BINARY(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`assets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`assets` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `UUID` BINARY(16) NOT NULL,
  `Name` TINYTEXT NOT NULL,
  `Code` VARCHAR(45) NOT NULL COMMENT 'EX: BRL, BTC, USD, NASQ:GOOG, B3:PETR4',
  `Fmt` VARCHAR(255) NOT NULL,
  `BookUUID` BINARY(16) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC),
  UNIQUE INDEX `Name_UNIQ` (`Name` ASC, `BookUUID` ASC),
  INDEX `fk_assets_1_idx` (`BookUUID` ASC),
  CONSTRAINT `fk_assets_1`
    FOREIGN KEY (`BookUUID`)
    REFERENCES `mydb`.`books` (`UUID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accounts` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `UUID` BINARY(16) NOT NULL,
  `ParentUUID` BINARY(16) NOT NULL,
  `Name` TINYTEXT NOT NULL,
  `BookUUID` BINARY(16) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC),
  UNIQUE INDEX `Name_UNIQ` (`Name` ASC, `BookUUID` ASC),
  INDEX `fk_accounts_1_idx` (`ParentUUID` ASC),
  INDEX `fk_accounts_2_idx` (`BookUUID` ASC),
  CONSTRAINT `fk_accounts_1`
    FOREIGN KEY (`ParentUUID`)
    REFERENCES `mydb`.`accounts` (`UUID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_accounts_2`
    FOREIGN KEY (`BookUUID`)
    REFERENCES `mydb`.`books` (`UUID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movements` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `UUID` BINARY(16) NOT NULL,
  `AccountUUID` BINARY(16) NOT NULL,
  `AssetUUID` BINARY(16) NOT NULL,
  `Ammount` BIGINT NOT NULL,
  `Status` CHAR(1) NOT NULL DEFAULT 'P' COMMENT '(P)Planned;(D)Done;(C)Cancelled',
  `LocalDate` INT(8) NOT NULL COMMENT 'Y*1E4 + M*1E2 + D\nEx: 20171231 = 2017-12-31',
  `Notes` TEXT(65535) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC),
  INDEX `fk_movements_1_idx` (`AssetUUID` ASC),
  INDEX `fk_movements_2_idx` (`AccountUUID` ASC),
  CONSTRAINT `fk_movements_1`
    FOREIGN KEY (`AssetUUID`)
    REFERENCES `mydb`.`assets` (`UUID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_movements_2`
    FOREIGN KEY (`AccountUUID`)
    REFERENCES `mydb`.`accounts` (`UUID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tags` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Table` VARCHAR(45) NOT NULL,
  `ItemUUID` BINARY(16) NOT NULL,
  `Tag` TINYTEXT NOT NULL,
  `BookUUID` BINARY(16) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UNIQ` (`ItemUUID` ASC, `Tag` ASC, `BookUUID` ASC),
  INDEX `fk_tags_1_idx` (`BookUUID` ASC),
  CONSTRAINT `fk_tags_1`
    FOREIGN KEY (`BookUUID`)
    REFERENCES `mydb`.`books` (`UUID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`itens` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `UUID` BINARY(16) NOT NULL,
  `AssetUUID` BINARY(16) NOT NULL,
  `Name` TINYTEXT NOT NULL,
  `GenericName` TINYTEXT NOT NULL,
  `Unit` VARCHAR(45) NOT NULL,
  `Qty` FLOAT NOT NULL,
  `UnitCost` BIGINT NOT NULL,
  `TotalCost` BIGINT NOT NULL,
  `PeriodStart` INT(8) NOT NULL COMMENT 'Y*1E4 + M*1E2 + D\nEx: 20171231 = 2017-12-31',
  `PeriodEnd` INT(8) NOT NULL COMMENT 'Y*1E4 + M*1E2 + D\nEx: 20171231 = 2017-12-31',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC),
  INDEX `fk_itens_1_idx` (`AssetUUID` ASC),
  CONSTRAINT `fk_itens_1`
    FOREIGN KEY (`AssetUUID`)
    REFERENCES `mydb`.`assets` (`UUID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transactions` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `UUID` BINARY(16) NOT NULL,
  `Name` TINYTEXT NOT NULL,
  `LocalDate` INT(8) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transactions_movements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transactions_movements` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `TransactionUUID` BINARY(16) NOT NULL,
  `MovementUUID` BINARY(16) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UNIQ` (`TransactionUUID` ASC, `MovementUUID` ASC),
  INDEX `fk_transactions_movements_2_idx` (`MovementUUID` ASC),
  CONSTRAINT `fk_transactions_movements_1`
    FOREIGN KEY (`TransactionUUID`)
    REFERENCES `mydb`.`transactions` (`UUID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transactions_movements_2`
    FOREIGN KEY (`MovementUUID`)
    REFERENCES `mydb`.`movements` (`UUID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transactions_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transactions_itens` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `TransactionUUID` BINARY(16) NOT NULL,
  `ItemUUID` BINARY(16) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UNIQ` (`TransactionUUID` ASC, `ItemUUID` ASC),
  INDEX `fk_transactions_itens_2_idx` (`ItemUUID` ASC),
  CONSTRAINT `fk_transactions_itens_1`
    FOREIGN KEY (`TransactionUUID`)
    REFERENCES `mydb`.`transactions` (`UUID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transactions_itens_2`
    FOREIGN KEY (`ItemUUID`)
    REFERENCES `mydb`.`itens` (`UUID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aseets_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aseets_values` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `UUID` BINARY(16) NOT NULL,
  `AssetUUID` BINARY(16) NOT NULL,
  `BaseUUID` BINARY(16) NOT NULL,
  `AssetInBase` FLOAT NOT NULL,
  `LocalDate` INT(8) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC),
  UNIQUE INDEX `UNIQ` (`BaseUUID` ASC, `AssetUUID` ASC, `LocalDate` ASC),
  CONSTRAINT `fk_aseets_value_1`
    FOREIGN KEY (`BaseUUID` , `AssetUUID`)
    REFERENCES `mydb`.`assets` (`UUID` , `UUID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
